id = "dart"
name = "Dart"
description = "Dart support."
version = "0.2.0"
schema_version = 1
authors = [
    "Abdullah Alsigar <abdullah.alsigar@gmail.com>",
    "Flo <flo80@users.noreply.github.com>",
    "ybbond <hi@ybbond.id>",
    "nielsenko <kasper@byolimit.com>"
]
repository = "https://github.com/zed-extensions/dart"

[language_servers.dart]
name = "Dart LSP"
language = "Dart"
languages = ["Dart"]

[grammars.dart]
repository = "https://github.com/UserNobody14/tree-sitter-dart"
commit = "80e23c07b64494f7e21090bb3450223ef0b192f4"
